### ISSUE TITLE
Hi! Does the input support an input with an irrational side length?

### ISSUE THREAD

**Issue by provenpeng** [dilsonpereira/chinese-postman-problem#1]
If my input is a right triangle, the hypotenuse is 2, and one of the right angles is 1, does that support the input, and if so, how?If not, any Suggestions?

**Comment by dilsonpereira** [comment]
Yes, but not symbolically. You have to calculate the value of the edges yourself and round them to some precision.

**Comment by provenpeng** [comment]
I also want to ask you, if I don't want to go back to the starting point, I just want to find the shortest path through all sides. What's the realization idea?please... =o=

**Comment by dilsonpereira** [comment]
Add a new point, connect it to all other points with 0 cost.
Find the cycle through all the points and then remove the new point.
